### ISSUE TITLE
Question: React JS Component

### ISSUE THREAD

**Issue by interpegasus** [tohjustin/coincharts#9]
Hi, Thank you for sharing the chart. It looks awesome.

I would like to know if is it possible to use the Chart as a React JS component that takes props (chart data)? 

Otherwise could you please provide some guidance on how to transform the code into a Chart component?

Thank you

**Comment by tohjustin** [comment]
Hi @interpegasus, currently there isn't a NPM package to import the chart component into your own project. Your best bet is to copy the source code in [https://github.com/tohjustin/coincharts/tree/master/src/components/Chart](https://github.com/tohjustin/coincharts/tree/master/src/components/Chart) & make any necessary changes for your own use case...

**Comment by interpegasus** [comment]
Thank you!
